### PR TITLE
Gmalc updates

### PR DESCRIPTION
**Pull request by GraemeMalcolm**
# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by GraemeMalcolm** [comment]
@sherzyang , I made a couple of changes to fix some issues and improve formatting. Please review and merge.

**Review by sherzyang — CHANGES_REQUESTED** [review]
Hi @GraemeMalcolm thanks for the updates! Could you remove the changes to "**&#8801;**"? While it visually looks nice, I was given instructions to remove those instances because they are not accessible. Then I can merge this PR.

**Review by sherzyang — APPROVED** [review]
@GraemeMalcolm I'm going to merge the change and then just remove the "**&#8801;**" icon mentions. Thanks!

**Comment by GraemeMalcolm** [comment]
We've used those throughout the portfolio without issue (and if the change is meant to help sight impaired learners, it's difficult to understand how "three lines" helps). What's the alt text that gets spoken by a screen reader for that button? "menu"? (There's no tooltip). We should use that with the HTML symbol code in parentheses for the first instance (to assist both sighted learners and those with visual impairment), then just "menu" (or whatever the screen reader says) - e g. "Select the menu (≡) icon..."

Cheers,
G
_____________________________________
Tiny keyboard, chubby fingers - sorry!
________________________________

**Pull request merged**
